title: Bryan Ramos-Morales
description: GIS, geography, environmental, and cultural resources portfolio
url: "https://bramosmorales.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

exclude:
  - README.md
